### ISSUE TITLE
ant build fails since 45360cc

### ISSUE THREAD

**Issue by perlundq** [perlundq/yajsync#2]
$ ant
Buildfile: /tmp/yajsync/build.xml

init:
    [mkdir] Created dir: /tmp/yajsync/build/classes
    [mkdir] Created dir: /tmp/yajsync/build/jar

build:
     [echo] YajSync: /tmp/yajsync/build.xml
    [javac] Compiling 81 source files to /tmp/yajsync/build/classes
    [javac] /tmp/yajsync/src/test/com/github/perlundq/yajsync/session/IntegerCoderTest.java:3: error: package org.junit does not exist
    [javac] import static org.junit.Assert.assertEquals;
    [javac]                        ^
...snip...
